# Generated by Django 5.1.2 on 2024-11-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlowFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("extension", models.CharField(max_length=10)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mpan_core", models.CharField(max_length=13)),
                ("bsc_validation_status", models.CharField(max_length=1)),
                ("mpan_site_visit_reason", models.CharField(max_length=2)),
                ("mpan_site_visit_additional_information", models.CharField(max_length=200)),
                ("meter_id", models.CharField(max_length=10)),
                ("meter_reading_type", models.CharField(max_length=1)),
                ("meter_reading_site_visit_reason", models.CharField(max_length=2)),
                ("meter_reading_site_visit_additional_information", models.CharField(max_length=200)),
                ("meter_register_id", models.CharField(max_length=2)),
                ("reading_at", models.DateTimeField(null=True)),
                ("register_reading", models.FloatField(null=True)),
                ("md_reset_at", models.DateTimeField(null=True)),
                ("number_of_md_resets", models.PositiveSmallIntegerField(null=True)),
                ("meter_reading_flag", models.CharField(max_length=1)),
                ("reading_method", models.CharField(max_length=1)),
                ("meter_reading_validation_result_reason", models.CharField(max_length=2)),
                ("meter_reading_validation_result_status", models.CharField(max_length=1)),
                ("register_reading_site_visit_reason", models.CharField(max_length=2)),
                ("register_reading_site_visit_additional_information", models.CharField(max_length=200)),
                (
                    "flow_file",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="meter_readings.flowfile"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlowFileMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("header_format", models.CharField(max_length=3)),
                ("footer_format", models.CharField(max_length=3)),
                ("file_identifier", models.CharField(max_length=10)),
                ("data_flow", models.CharField(max_length=5)),
                ("data_flow_version", models.SmallIntegerField()),
                ("from_market_participant_role_code", models.CharField(max_length=1)),
                ("from_market_participant_id", models.CharField(max_length=4)),
                ("to_market_participant_role_code", models.CharField(max_length=1)),
                ("to_market_participant_id", models.CharField(max_length=4)),
                ("sending_application_id", models.CharField(max_length=5)),
                ("receiving_application_id", models.CharField(max_length=5)),
                ("broadcast", models.CharField(max_length=1)),
                ("test_data_flag", models.CharField(max_length=4)),
                ("total_group_count", models.CharField(max_length=5)),
                ("footer_checksum", models.SmallIntegerField(blank=True, null=True)),
                ("flow_count", models.CharField(max_length=1)),
                ("file_created_at", models.DateTimeField()),
                ("file_completed_at", models.DateTimeField()),
                (
                    "flow_file",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="meter_readings.flowfile"),
                ),
            ],
        ),
    ]
